INSERT INTO "CURRENCY_EXCHANGE" (ID, CURRENCY_FROM, CURRENCY_TO, CONVERSION_MULTIPLE, ENV) 
VALUES (10000,'USD', 'INR', 65, '');
INSERT INTO "CURRENCY_EXCHANGE" (ID, CURRENCY_FROM, CURRENCY_TO, CONVERSION_MULTIPLE, ENV) 
VALUES (10001,'USD', 'MXP', 20, '');
INSERT INTO "CURRENCY_EXCHANGE" (ID, CURRENCY_FROM, CURRENCY_TO, CONVERSION_MULTIPLE, ENV) 
VALUES (10002,'USD', 'EUR', 25, '');